### ISSUE TITLE
Citations or footnotes?

### ISSUE THREAD

**Issue by devinberg** [RatulSaha/presento#4]
I'm trying to insert citations in my Presento slide deck using \footfullcite. However, nothing is displayed at the bottom of the frame. I also tried just manually formatting a citation using a footnote but this doesn't seem to display either. Is this possible with Presento?

**Comment by RatulSaha** [comment]
This is very interesting. Could you give me a minimal (non-)working example?

**Comment by devinberg** [comment]
Here is an example where I imported the Presento template and added some bib items and a footnote. https://github.com/devinberg/presentation-open-engineering

I'm referencing this for help: https://tex.stackexchange.com/questions/5836/place-bibliography-items-at-bottom-of-frame

**Comment by RatulSaha** [comment]
I understand the situation now. The footer is actually [modified](https://github.com/RatulSaha/presento/blob/4fc1786da9c4b70296b50e9842e20a21bdbb0a9f/config/presento.sty#L49) in presento.sty, which is why your expected try is not working.

While you can definitely improve this by editing the style file, I would recommend against putting unknown amount of content (references most of the cases are) in the footer of beamer. That would break the design. I'd suggest to manually mention much smaller (than the usual Bibtex output) hand-typed reference inside the slides and not in the footer.

Please open the issue again if you have further question.
